name: example-group-1

description: This is a test group

directory_roles:
  - role_name: Global Reader

subscription_roles:
  - role_name: Reader
    resources_scopes:
      - /subscriptions/00000000-0000-0000-0000-000000000000

management_group_roles:
  - role_name: Reader
    resources_scopes:
      - /providers/Microsoft.Management/managementGroups/00000000-0000-0000-0000-000000000000

pim_maximum_duration_hours: 12
pim_require_justification: true

owners:
  - type: user
    email: user-1@example.com
    pim:
      type: Eligible

members:

  - type: user
    email: user-2@example.com 
    pim:
      type: Eligible

  - type: user
    object_id: 00000000-0000-0000-0000-000000000000
    pim:
      type: Eligible

  - type: user
    display_name: example-group-2
    pim:
      type: Active

  - type: service_principal
    object_id: 00000000-0000-0000-0000-000000000000
    pim:
      type: Active
