apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: karpenter-firestartr-pre
spec:
  amiFamily: AL2023 # Amazon Linux 2023
  role: "Karpenter-firestartr-pre"
  subnetSelectorTerms:
    - tags:
        application: "firestartr"
        environment: "pre"
        kubernetes.io/role/internal-elb: "1"
  securityGroupSelectorTerms:
    - tags:
        "kubernetes.io/cluster/firestartr-pre": "owned"
  amiSelectorTerms:
  - name: "amazon-eks-node-al2023-x86_64-standard-1.33-*"
  tags:
    Project: "firestartr"
    Cluster: "firestartr-pre"
    ManagedBy: "karpenter"
    billing-team: "platform"
    GithubRepo: "infra"
    GithubOrg: "prefapp"
    Environment: "pre-worker"
    Backup: "enabled"
    Monitoring: "enabled"
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      volumeSize: 100Gi
      volumeType: gp3
      encrypted: true
