apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: karpenter-on-demand-default
spec:
  template:
    metadata:
      labels:
        billing-team: platform
        type: runners
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
          - m6a.large
          - m6a.xlarge
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["m"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["5"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: karpenter-on-demand-default
      expireAfter: 168h # 7 * 24h = 168h
  limits:
    cpu: 40
    memory: "160Gi"
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5m
  weight: 10

