variable "resource_group" {
  type        = string
  description = "Name of the existing resource group that hosts the server and lookup resources."
}

variable "password_length" {
  type        = number
  default     = 20
  description = "Length of the password generated by `random_password.password` before storing it in Key Vault."
}

variable "subnet_name" {
  type        = string
  default     = null
  description = "Subnet name for private access; used when `public_network_access_enabled` is false."
}

variable "dns_private_zone_name" {
  type        = string
  default     = null
  description = "Private DNS zone name for the flexible server when using private networking."
}

variable "key_vault" {
  type = object({
    name                = optional(string)
    resource_group_name = optional(string)
    tags                = optional(map(string))
  })
  default     = {}
  description = "Key Vault lookup by `name` + `resource_group_name`, or by `tags` via `azurerm_resources` when the tags map is non-empty."
}

variable "administrator_password_key_vault_secret_name" {
  type        = string
  description = "Required name of the Key Vault secret for the PostgreSQL administrator password (read by `data.azurerm_key_vault_secret`, written by `azurerm_key_vault_secret.password_create`)."

  validation {
    condition     = trimspace(var.administrator_password_key_vault_secret_name) != ""
    error_message = "administrator_password_key_vault_secret_name must be a non-empty Key Vault secret name."
  }
}

variable "tags_from_rg" {
  type        = bool
  default     = false
  description = "When true, merge the resource group tags with `tags` (latter wins on key conflicts)."
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Tags applied to the flexible server."
}

variable "postgresql_flexible_server" {
  type = object({
    name                              = string
    location                          = string
    version                           = optional(number)
    public_network_access_enabled     = optional(bool)
    administrator_login               = optional(string)
    zone                              = optional(string)
    storage_tier                      = optional(string)
    storage_mb                        = optional(number)
    sku_name                          = optional(string)
    replication_role                  = optional(string)
    create_mode                       = optional(string)
    source_server_id                  = optional(string)
    point_in_time_restore_time_in_utc = optional(string)
    backup_retention_days             = optional(number)
    maintenance_window = optional(object({
      day_of_week  = number
      start_hour   = number
      start_minute = number
    }))
    authentication = optional(object({
      active_directory_auth_enabled = bool
      password_auth_enabled         = bool
      tenant_id                     = optional(string)
    }))
  })
  description = "Flexible Server settings. Nested `maintenance_window` and `authentication` blocks are always rendered; supply them in normal use."
}

variable "vnet" {
  type = object({
    name                = optional(string)
    resource_group_name = optional(string)
    tags                = optional(map(string))
  })
  default     = {}
  description = "Virtual network: use `name` and `resource_group_name`, and/or `tags` for `azurerm_resources` lookup."
}

variable "postgresql_flexible_server_configuration" {
  type = map(object({
    name  = optional(string)
    value = optional(string)
  }))
  description = "Map of PostgreSQL server configuration parameters (`azurerm_postgresql_flexible_server_configuration`)."
}

variable "firewall_rule" {
  type = list(object({
    name             = optional(string)
    start_ip_address = optional(string)
    end_ip_address   = optional(string)
  }))
  default     = []
  description = "Firewall rules for public access; entries with `name == null` are skipped."
}
