variable "resource_group" {
  type        = string
  description = "Name of the existing resource group referenced by `data.azurerm_resource_group.resource_group` (server and lookups)."
}

variable "password_length" {
  type        = number
  default     = 20
  description = "Length of the random password generated by `random_password.password` before it is written to Key Vault."
}

variable "subnet_name" {
  type        = string
  default     = null
  description = "Subnet delegated for PostgreSQL when `public_network_access_enabled` is false; required together with VNet resolution and private DNS for private access."
}

variable "dns_private_zone_name" {
  type        = string
  default     = null
  description = "Private DNS zone name linked to the flexible server when using private networking."
}

variable "key_vault" {
  type = object({
    name                = optional(string)
    resource_group_name = optional(string)
    tags                = optional(map(string))
  })
  default     = {}
  description = "Locate the Key Vault either via `name` + `resource_group_name` together, or via non-empty `tags` used as `required_tags` on `azurerm_resources`."

  validation {
    condition = (
      (
        try(var.key_vault.name, null) != null &&
        try(var.key_vault.resource_group_name, null) != null
      ) ||
      length(try(var.key_vault.tags, {})) > 0
    )
    error_message = "key_vault must be specified either with both `name` and `resource_group_name`, or with non-empty `tags`."
  }

  validation {
    condition = (
      (try(var.key_vault.name, null) == null && try(var.key_vault.resource_group_name, null) == null) ||
      (try(var.key_vault.name, null) != null && try(var.key_vault.resource_group_name, null) != null)
    )
    error_message = "When using name-based Key Vault lookup, both `name` and `resource_group_name` must be provided together."
  }
}

variable "administrator_password_key_vault_secret_name" {
  type        = string
  default     = null
  description = "Secret name in Key Vault for the server admin password. The module reads it via `data.azurerm_key_vault_secret` and writes an initial value from `random_password` with `azurerm_key_vault_secret.password_create` (value changes ignored after first set)."
}

variable "tags_from_rg" {
  type        = bool
  default     = false
  description = "Merge tags from the resource group with `tags` (module tags win on duplicate keys)."
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Tags applied to the flexible server."
}

variable "postgresql_flexible_server" {
  type = object({
    name                              = string
    location                          = string
    version                           = optional(number)
    public_network_access_enabled     = optional(bool)
    administrator_login               = optional(string)
    zone                              = optional(string)
    storage_tier                      = optional(string)
    storage_mb                        = optional(number)
    sku_name                          = optional(string)
    replication_role                  = optional(string)
    create_mode                       = optional(string)
    source_server_id                  = optional(string)
    point_in_time_restore_time_in_utc = optional(string)
    backup_retention_days             = optional(number)
    maintenance_window = optional(object({
      day_of_week  = number
      start_hour   = number
      start_minute = number
    }))
    authentication = optional(object({
      active_directory_auth_enabled = bool
      password_auth_enabled         = bool
      tenant_id                     = optional(string)
    }))
  })
  description = <<-EOT
    Flexible Server settings. The resource always renders `maintenance_window` and `authentication` nested blocks from this object; in practice you should supply both objects even though the type marks them optional, or the plan can fail on null attributes.
    `lifecycle.ignore_changes` ignores `version`, `create_mode`, `point_in_time_restore_time_in_utc`, `source_server_id`, and `zone` after creation.
  EOT
}

variable "vnet" {
  type = object({
    name                = optional(string)
    resource_group_name = optional(string)
    tags                = optional(map(string))
  })
  default     = {}
  description = "Virtual network lookup by `name` + `resource_group_name`, or by `tags` via `azurerm_resources` when private connectivity is used."
}

variable "postgresql_flexible_server_configuration" {
  type = map(object({
    name  = optional(string)
    value = optional(string)
  }))
  default     = {}
  description = "Server parameters as a map; each entry sets `azurerm_postgresql_flexible_server_configuration` (typically use stable keys and set `name`/`value` per entry)."
}

variable "firewall_rule" {
  type = list(object({
    name             = optional(string)
    start_ip_address = optional(string)
    end_ip_address   = optional(string)
  }))
  default     = []
  description = "Firewall rules when public network access is enabled; entries with `name == null` are skipped."
}
